- name: download ZABBIX Repo - Centos/RHEL 7
  get_url:
    url: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    dest: /tmp/zabbix.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: install ZABBIX Repo - Centos/RHEL 7
  yum:
    name: /tmp/zabbix.rpm
    state: present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: add port(10050) for zabbix-server
  firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: install zabbix-agent
  yum:
    name: zabbix-agent
    enablerepo: zabbix
    state: latest

- name: get ServerName
  shell: hostname
  register: ServerName
# - debug: var=ServerName

- name: setting zabbix_agent.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '{{ item.regexp }}'
    insertafter: '{{ item.insertafter }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^Server='
      insertafter: '^# Server='
      line: 'Server=zabbix'
    - regexp: '^ServerActive='
      insertafter: '^# ServerActive='
      line: 'ServerActive=zabbix'
    - regexp: '^Hostname='
      insertafter: '^# Hostname='
      line: 'Hostname={{ ServerName.stdout }}'

- name: start and enabled zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes
