- name: install httpd
  yum:
    name: httpd
    state: latest

- name: start httpd and enabled
  service:
    name: httpd
    state: started
    enabled: yes

- name: add port(80)
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  notify: reload firewalld

- name: add service
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify: reload firewalld

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
